version: 2.1

jobs:
  release:
    working_directory: ~/mixed-monorepo-js
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Install Slack bot for semantic-release.
          command: npm i -g semantic-release semantic-release-slack-bot
      - run:
          name: Run semantic release
          command: npx semantic-release


workflows:
  version: 2

  release:
    jobs:
      - release:
          filters:
            branches:
              only:
                - master
