version: 2.1

jobs:
  split_and_push:
    working_directory: ~/mixed-monorepo-js
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: Install app
          command: yarn install
      - run:
          name: Run semantic release
          command: yarn run semantic-release


workflows:
  version: 2

  release:
    jobs:
      - split_and_push:
          filters:
            branches:
              only:
                - master
